import { Router } from "express";
import authRoutes from "./auth.routes";
import userRoutes from "./user.routes";
import courseRoutes from "./course.routes";
import batchRoutes from "./batch.routes";
import feeRoutes from "./fee.routes";
import jobRoutes from "./job.routes";
import announcementRoutes from "./announcement.routes";
import auditLogRoutes from "./auditLog.routes";
import moduleRoutes from "./module.routes";
import lessonRoutes from "./lesson.routes";
import materialRoutes from "./material.routes";
import classScheduleRoutes from "./classSchedule.routes";
import attendanceRoutes from "./attendance.routes";
import taskRoutes from "./task.routes";
import submissionRoutes from "./submission.routes";
import mockInterviewRoutes from "./mockInterview.routes";
import trainerDashboardRoutes from "./trainerDashboard.routes";
import progressRoutes from "./progress.routes";

const router = Router();

router.use("/auth", authRoutes);
router.use("/users", userRoutes);
router.use("/courses", courseRoutes);
router.use("/batches", batchRoutes);
router.use("/fees", feeRoutes);
router.use("/jobs", jobRoutes);
router.use("/announcements", announcementRoutes);
router.use("/audit-logs", auditLogRoutes);
router.use("/modules", moduleRoutes);
router.use("/lessons", lessonRoutes);
router.use("/materials", materialRoutes);
router.use("/classes", classScheduleRoutes);
router.use("/attendance", attendanceRoutes);
router.use("/tasks", taskRoutes);
router.use("/submissions", submissionRoutes);
router.use("/interviews", mockInterviewRoutes);
router.use("/dashboard", trainerDashboardRoutes);
router.use("/progress", progressRoutes);

export default router;
