import type { CurriculumCourseDef, CurriculumModuleDef } from "./types";

const wordpressFundamentals: CurriculumModuleDef = {
  name: "WordPress Fundamentals",
  description: "What WordPress actually is, how the web hosting it works, and getting a real install running.",
  estimatedDuration: "1 week",
  topics: [
    {
      name: "WordPress Overview",
      lessons: [
    {
      title: "What is WordPress?",
      description: "The software behind a huge share of the websites you visit every day.",
      estimatedMinutes: 12,
      difficulty: "BEGINNER",
      whatIsIt: "WordPress is free, open-source software that runs on a web server and lets you create and manage a website's content — pages, blog posts, images — through a visual dashboard instead of writing raw code for every page.",
      whyItMatters: "Before tools like WordPress existed, adding a single new paragraph to a website meant a developer editing HTML files by hand and re-uploading them. WordPress separates 'who writes the content' from 'who builds the website's engine,' so non-technical people can publish independently.",
      analogy: "Think of WordPress like a print magazine's production system. The printing press and layout templates (WordPress core and themes) stay the same issue after issue, but editors can drop in new articles and photos (content) each week without touching the machinery.",
      simpleExample: "A local gym owner can log in, click 'Add New Post,' type up this month's class schedule, hit Publish, and it's live on their website within seconds — no developer required.",
      technicalExplanation: "WordPress is a PHP application that stores structured content — posts, pages, settings, comments — in a MySQL (or MariaDB) database. When a visitor requests a page, WordPress runs PHP code that queries the database, passes the results through the active theme's templates, and returns finished HTML to the browser.",
      codeExamples: [],
      realWorldUsage: "WordPress runs personal blogs, small business sites, news outlets, university pages, and full online stores through WooCommerce — it scales from a single freelancer's portfolio to sites handling millions of visits a month.",
      commonMistakes: [
        {
          wrong: "Assuming WordPress is only good for blogs because it started as blogging software.",
          right: "Modern WordPress, combined with custom post types and page builders, is used to build almost any kind of website: e-commerce stores, membership sites, portfolios, directories, and more.",
          explanation: "WordPress evolved from a blogging tool into a general-purpose CMS; its blog origins are historical, not a limitation on what you can build today.",
        },
      ],
      practice: {
        instructions: "List three websites you personally visit or use that might be built on WordPress, then use a tool like 'IsItWP' or the browser's page source (search for 'wp-content') to check if you're right.",
        hint: "Sites with a URL containing '/wp-content/' or '/wp-json/' in their source are running WordPress.",
      },
      quiz: [
        {
          question: "What does WordPress primarily let a non-technical user do?",
          options: [
            "Write raw HTML faster",
            "Manage website content through a visual dashboard without hand-editing code",
            "Design a company logo",
            "Host a website for free forever",
          ],
          correctIndex: 1,
          explanation: "WordPress's core value is letting people manage content — pages, posts, media — without editing code directly.",
        },
        {
          question: "Where does WordPress store a site's posts, pages, and settings?",
          options: ["In plain text files only", "In a MySQL/MariaDB database", "In the browser's memory", "In the theme's CSS file"],
          correctIndex: 1,
          explanation: "WordPress stores structured content in a database, and PHP code retrieves and displays it through templates.",
        },
        {
          question: "A small business owner asks why they should use WordPress instead of hiring a developer to hand-code a five-page site. What's the strongest reason?",
          options: [
            "Hand-coded sites are always slower",
            "WordPress lets them update content themselves later without needing a developer for every change",
            "WordPress sites never need hosting",
            "Hand-coded sites can't use a domain name",
          ],
          correctIndex: 1,
          explanation: "The core value proposition of a CMS like WordPress is ongoing independence — the owner can edit text, swap images, and add posts themselves long after launch, without paying a developer for routine content changes.",
        },
        {
          question: "Which of these is an accurate description of the relationship between WordPress core, themes, and content?",
          options: [
            "Themes store the content; WordPress core only handles login",
            "WordPress core and the active theme define structure and design, while content lives independently in the database",
            "Content is stored inside the theme's files",
            "WordPress core changes every time a new post is published",
          ],
          correctIndex: 1,
          explanation: "Content (posts, pages) is stored in the database independently of the theme, which is why you can switch themes without losing your content.",
        },
        {
          question: "A client says 'I don't want to touch any code, I just want to log in and write articles.' Which WordPress trait makes this possible?",
          options: [
            "WordPress requires FTP access for every edit",
            "The visual dashboard lets users create and publish content without editing HTML/PHP directly",
            "WordPress has no database",
            "WordPress only works for developers",
          ],
          correctIndex: 1,
          explanation: "The dashboard's visual editor is exactly the layer that lets non-technical users manage content without touching the underlying code.",
        },
      ],
      rememberThis: "WordPress is the printing press that stays put while the articles change every week.",
      keyTakeaways: [
        "WordPress is free, open-source CMS software, not a hosting service itself.",
        "It's built on PHP and stores content in a MySQL database.",
        "It separates content management from the underlying code, so non-developers can publish.",
        "It has grown far beyond blogging into stores, portfolios, and full business sites.",
      ],
    },
    {
      title: "WordPress.com vs WordPress.org",
      description: "The single most confusing naming decision in the WordPress world, cleared up.",
      estimatedMinutes: 12,
      difficulty: "BEGINNER",
      whatIsIt: "WordPress.org is where you download the free WordPress software to install on hosting you choose yourself, giving full control. WordPress.com is a company (Automattic) that hosts WordPress for you on its own servers, but restricts plugins, themes, and customization unless you pay for higher-tier plans.",
      whyItMatters: "Every professional WordPress developer works with the self-hosted WordPress.org software, because client projects almost always need custom plugins, themes, or code that WordPress.com's lower tiers simply don't allow.",
      analogy: "It's the difference between renting a fully-managed serviced apartment (WordPress.com) where the landlord decides what you can and can't install, versus buying your own house (WordPress.org) where you own the land and can renovate however you like.",
      simpleExample: "A freelance developer building a custom online store for a client would use WordPress.org on independent hosting so they can install WooCommerce and any custom plugin the project needs — something the WordPress.com free plan won't allow.",
      technicalExplanation: "WordPress.org distributes the WordPress core codebase (PHP files) that you install on any server meeting its requirements (PHP, MySQL, a web server like Apache or Nginx). WordPress.com runs that same core codebase on its own multi-tenant infrastructure and gates access to file editing, custom plugins, and custom themes behind its Business/Commerce plans.",
      codeExamples: [],
      realWorldUsage: "Agencies, freelancers, and businesses that need custom functionality almost always choose self-hosted WordPress.org with a hosting provider like SiteGround, Bluehost, or Kinsey. WordPress.com suits hobbyists who want zero server maintenance and don't need custom code.",
      commonMistakes: [
        {
          wrong: "Signing up for a free WordPress.com blog and then trying to install a custom plugin, only to find the option missing.",
          right: "Check what a hosting/plan option actually allows before starting a client project — for real development work, choose WordPress.org with your own hosting from day one.",
          explanation: "Free and low-tier WordPress.com plans intentionally block custom plugin/theme uploads to keep their hosting simple and secure, which is a dead end for development work.",
        },
      ],
      practice: {
        instructions: "Write down two scenarios: one where WordPress.com's hosted service would be the right choice, and one where WordPress.org (self-hosted) is necessary. Justify each with a specific feature requirement.",
        hint: "Think about a hobby blogger with zero technical skill versus a business needing a custom booking plugin.",
      },
      quiz: [
        {
          question: "Which option gives you full control over installing any plugin or theme?",
          options: ["WordPress.com free plan", "WordPress.org (self-hosted)", "Both give identical control", "Neither allows plugins"],
          correctIndex: 1,
          explanation: "Self-hosted WordPress.org gives complete control over hosting, plugins, and themes since you manage the server yourself.",
        },
        {
          question: "Who hosts your site if you use WordPress.com?",
          options: ["You, on your own server", "Automattic, on their infrastructure", "No one — it runs in the browser", "Your domain registrar"],
          correctIndex: 1,
          explanation: "WordPress.com is a hosted service run by Automattic; you don't manage the underlying server.",
        },
        {
          question: "A freelancer is hired to build a custom booking system with a plugin that doesn't exist yet, requiring custom PHP code. Which option should they choose?",
          options: [
            "WordPress.com free plan",
            "WordPress.com Personal plan",
            "Self-hosted WordPress.org",
            "Either, they're functionally identical",
          ],
          correctIndex: 2,
          explanation: "Only self-hosted WordPress.org allows uploading arbitrary custom plugins and code; WordPress.com's lower tiers block this entirely.",
        },
        {
          question: "A hobby blogger with no technical background wants zero server maintenance and doesn't need custom plugins. Which is the more practical choice?",
          options: [
            "WordPress.org with a VPS they manage themselves",
            "WordPress.com's hosted plans",
            "Building a site from scratch in raw HTML",
            "There is no suitable WordPress option for them",
          ],
          correctIndex: 1,
          explanation: "WordPress.com removes all server management responsibility, which fits a non-technical hobbyist with modest needs far better than self-managing hosting.",
        },
        {
          question: "Why can both WordPress.com and WordPress.org be called 'WordPress' even though they behave so differently?",
          options: [
            "They are unrelated products that share a name by coincidence",
            "WordPress.com runs the same underlying WordPress core software, just on Automattic's managed infrastructure with restrictions",
            "WordPress.org is a rebranded version of WordPress.com",
            "Only WordPress.org is real WordPress software",
          ],
          correctIndex: 1,
          explanation: "Both are built on the same open-source WordPress codebase; the difference is who hosts it and how much of it you're allowed to modify.",
        },
      ],
      rememberThis: "WordPress.org is the house you own; WordPress.com is the apartment you rent from someone else's rules.",
      keyTakeaways: [
        "WordPress.org: free software you self-host, full control over plugins/themes/code.",
        "WordPress.com: a hosted service with restrictions on lower-tier plans.",
        "Professional development work almost always uses self-hosted WordPress.org.",
        "The two share the same underlying WordPress software but differ in who controls the server.",
      ],
    },
      ],
    },
    {
      name: "Setting Up the Infrastructure",
      lessons: [
    {
      title: "Domain Names & Hosting Basics",
      description: "The two things every website needs before it can exist online.",
      estimatedMinutes: 15,
      difficulty: "BEGINNER",
      whatIsIt: "A domain name is the human-readable address people type to find your site (like example.com). Web hosting is the actual computer (server) that stores your site's files and database and serves them to visitors 24/7.",
      whyItMatters: "WordPress software has to live somewhere and be reachable by a memorable name — without hosting, there's no server to run it on; without a domain, visitors would have to type a raw IP address to find you.",
      analogy: "Hosting is like renting a physical shop unit where your business actually operates — shelves, storage, the building itself. The domain name is the street address on the sign out front that tells customers where to find that shop.",
      simpleExample: "A bakery buys the domain 'sweettreatsbakery.com' from a registrar and rents hosting space from a provider like Hostinger, where the actual WordPress files and photos of cakes are stored.",
      technicalExplanation: "A domain name is registered through a registrar (e.g. GoDaddy, Namecheap) and points, via DNS records, to the IP address of a hosting server. The hosting provider allocates disk space, CPU, and RAM to run the web server software (Apache/Nginx), PHP, and MySQL that WordPress depends on.",
      codeExamples: [],
      realWorldUsage: "Every WordPress project starts with these two purchases: a domain name and a hosting plan (shared, VPS, or managed WordPress hosting), before WordPress itself is ever installed.",
      commonMistakes: [
        {
          wrong: "Buying a domain and hosting from two completely unrelated providers and assuming the site will 'just work' immediately.",
          right: "After buying a domain and hosting separately, you must explicitly point the domain's DNS/nameservers to the hosting provider before the site becomes reachable at that domain.",
          explanation: "A domain and hosting account are independent purchases until you connect them via DNS settings — skipping this step is one of the most common beginner setup errors.",
        },
      ],
      practice: {
        instructions: "Visit a domain registrar's website (e.g. Namecheap) and search for three domain name ideas for a fictional business of your choosing. Note which are available and their yearly price.",
        hint: "Try variations with different TLDs (.com, .in, .co) if your first choice is taken.",
      },
      quiz: [
        {
          question: "What does web hosting actually provide?",
          options: [
            "A memorable name for your website",
            "The server storage and computing power that runs your website's files",
            "Free email addresses only",
            "A logo design service",
          ],
          correctIndex: 1,
          explanation: "Hosting is the physical/virtual server space where your website's files and database actually live and run.",
        },
        {
          question: "What must you do after buying a domain and hosting from different companies?",
          options: [
            "Nothing, they connect automatically",
            "Point the domain's DNS/nameservers to the hosting provider",
            "Delete the domain and buy a new one",
            "Contact WordPress.org support",
          ],
          correctIndex: 1,
          explanation: "You need to update the domain's DNS settings so it resolves to your hosting provider's servers.",
        },
        {
          question: "A client already owns 'mybakery.com' from a previous employee but has no hosting yet. What's the correct next step to launch a WordPress site there?",
          options: [
            "Buy the domain again from a different registrar",
            "Sign up for a hosting plan and point the existing domain's DNS/nameservers to it",
            "WordPress can run without any hosting",
            "Delete the domain and start fresh",
          ],
          correctIndex: 1,
          explanation: "The existing domain can be reused — it just needs to be pointed, via DNS, at wherever the new hosting account lives.",
        },
        {
          question: "Why can't WordPress simply run 'in the domain' without a separate hosting plan?",
          options: [
            "A domain name is only an address/label; it has no server or storage to run software on",
            "WordPress requires two domains at once",
            "Domains include free hosting by default",
            "Hosting is only needed for images, not for WordPress itself",
          ],
          correctIndex: 0,
          explanation: "A domain is just a human-readable pointer; the actual files, database, and PHP execution environment WordPress needs live on a hosting server.",
        },
        {
          question: "A business wants to move their WordPress site to a new, faster hosting provider but keep the same web address. What has to happen?",
          options: [
            "They must buy a brand-new domain name",
            "The site files/database are migrated to new hosting and the domain's DNS is repointed to it",
            "Nothing — hosting providers share sites automatically",
            "WordPress must be reinstalled from scratch with no way to keep the URL",
          ],
          correctIndex: 1,
          explanation: "Migrating hosts means moving the WordPress files and database to the new server and then updating DNS so the same domain resolves to the new location.",
        },
      ],
      rememberThis: "The domain is the sign out front; hosting is the building the shop actually operates in.",
      keyTakeaways: [
        "A domain name is the human-friendly address for your site.",
        "Hosting is the server that stores and runs your site's files and database.",
        "These are usually two separate purchases that must be connected via DNS.",
        "WordPress needs hosting that supports PHP and MySQL to run.",
      ],
    },
    {
      title: "DNS & SSL Basics",
      description: "How a domain name finds the right server, and how HTTPS keeps that connection secure.",
      estimatedMinutes: 16,
      difficulty: "BEGINNER",
      whatIsIt: "DNS (Domain Name System) is the internet's phonebook — it translates human-readable domain names into the numeric IP addresses computers actually use to find each other. SSL/TLS is a security layer that encrypts the data traveling between a visitor's browser and your server, shown as the padlock and 'https://' in the address bar.",
      whyItMatters: "Without DNS, you'd have to remember and type a server's raw IP address to visit any website. Without SSL, any data submitted on your site (passwords, payment details, contact forms) would travel in plain text that anyone on the network could read.",
      analogy: "DNS is like a contacts app on your phone — you tap a person's name, and it looks up their actual phone number behind the scenes so you don't have to memorize it. SSL is like sealing a letter in a tamper-evident envelope so nobody can read or alter it in transit.",
      simpleExample: "When you type 'example.com,' DNS quietly looks up that its server lives at an address like 93.184.216.34, connects you there, and if SSL is set up, you'll see a padlock icon confirming the connection is encrypted.",
      technicalExplanation: "DNS resolution uses records such as A records (pointing a domain to an IPv4 address), CNAME records (aliasing one domain to another), and NS records (specifying which nameservers are authoritative for the domain). SSL/TLS certificates are issued by a Certificate Authority, bind a public/private key pair to your domain, and enable encrypted HTTPS connections; most modern hosts offer free certificates via Let's Encrypt.",
      codeExamples: [
        {
          title: "Checking a domain's DNS A record from the command line",
          language: "bash",
          code: "nslookup example.com\n# or on Linux/macOS:\ndig example.com A",
          explanation: "Both commands query DNS servers to find the IP address that a domain currently resolves to, which is useful for confirming DNS changes have taken effect before a site goes live.",
        },
      ],
      realWorldUsage: "Every WordPress site launch involves pointing DNS correctly and enabling an SSL certificate — most managed WordPress hosts (Kinsta, WP Engine, SiteGround) now auto-install free SSL certificates during setup.",
      commonMistakes: [
        {
          wrong: "Expecting DNS changes to appear instantly worldwide after updating them.",
          right: "Treat DNS changes as taking anywhere from a few minutes up to 24-48 hours to fully propagate globally, and avoid making unrelated changes during that window.",
          explanation: "DNS records are cached by servers around the world for a period called TTL (time to live); until those caches expire, some visitors will still see the old settings.",
        },
      ],
      practice: {
        instructions: "Run 'nslookup' (Windows) or 'dig' (Mac/Linux) against three different websites and record the IP addresses returned. Then check whether each site shows a valid padlock/HTTPS in your browser.",
        hint: "Open your terminal/command prompt and type: nslookup wordpress.org",
      },
      quiz: [
        {
          question: "What does DNS primarily do?",
          options: [
            "Encrypts data between browser and server",
            "Translates domain names into IP addresses",
            "Stores website content",
            "Registers a business name legally",
          ],
          correctIndex: 1,
          explanation: "DNS is the system that resolves human-readable domain names to the numeric IP addresses servers use.",
        },
        {
          question: "What does an SSL/TLS certificate provide?",
          options: [
            "A faster DNS lookup",
            "Encrypted, secure communication between browser and server (HTTPS)",
            "Free hosting",
            "Automatic backups",
          ],
          correctIndex: 1,
          explanation: "SSL/TLS certificates enable HTTPS, encrypting data in transit so it can't be easily intercepted or read.",
        },
        {
          question: "A client just updated their domain's nameservers to point to a new host, but the site still shows the old host's content an hour later. What's the most likely explanation?",
          options: [
            "The domain was registered incorrectly",
            "DNS propagation hasn't completed yet due to caching (TTL)",
            "WordPress is broken",
            "SSL certificates take a week to activate",
          ],
          correctIndex: 1,
          explanation: "DNS changes propagate gradually as cached records expire around the world; seeing old content briefly after a change is expected, not a sign of a broken setup.",
        },
        {
          question: "A site owner sees a 'Not Secure' warning in the browser address bar for their WordPress site. What is most likely missing?",
          options: [
            "A properly installed SSL/TLS certificate enabling HTTPS",
            "A valid DNS A record",
            "A WordPress theme",
            "A category structure",
          ],
          correctIndex: 0,
          explanation: "The 'Not Secure' warning specifically indicates the connection isn't encrypted, meaning no valid SSL/TLS certificate is active for HTTPS.",
        },
        {
          question: "Before launching a site on new hosting, a developer wants to confirm DNS changes have taken effect. What's a practical way to check?",
          options: [
            "Reinstall WordPress",
            "Run nslookup or dig against the domain to see which IP address it currently resolves to",
            "Clear the WordPress cache plugin",
            "Change the site's permalink structure",
          ],
          correctIndex: 1,
          explanation: "nslookup/dig query DNS directly and show the IP a domain currently resolves to, confirming whether propagation to the new host has completed.",
        },
      ],
      rememberThis: "DNS is your contacts app for the internet; SSL is the sealed envelope that keeps what you send private.",
      keyTakeaways: [
        "DNS translates domain names into IP addresses computers use to connect.",
        "DNS changes can take time to propagate globally due to caching (TTL).",
        "SSL/TLS encrypts traffic between browser and server, shown as HTTPS.",
        "Most hosts now offer free SSL certificates via Let's Encrypt.",
      ],
    },
    {
      title: "Installing WordPress",
      description: "Getting an actual, working WordPress site running for the first time.",
      estimatedMinutes: 20,
      difficulty: "BEGINNER",
      whatIsIt: "Installing WordPress means getting the WordPress software files onto a hosting server, creating a database for it to use, and running its short setup wizard to create your first admin account — after which your site is live and manageable through the dashboard.",
      whyItMatters: "Everything else you'll learn — themes, plugins, content — depends on having a working WordPress installation to apply it to. Most hosts have simplified this to a one-click process, but understanding the manual steps helps you troubleshoot when something goes wrong.",
      analogy: "Installing WordPress is like assembling a new kitchen before you can cook anything in it — you're connecting the stove to gas (database), running the water lines (config), and doing a final inspection (setup wizard) before you can actually start making meals (content).",
      simpleExample: "A user picks a hosting plan, clicks 'Install WordPress' in their hosting control panel, chooses a site title and admin username/password, and within a minute has a live WordPress dashboard to log into.",
      technicalExplanation: "A manual WordPress install involves: creating a MySQL database and a database user with privileges on it, uploading the WordPress core files (downloaded from wordpress.org) to the server via FTP or a file manager, creating a wp-config.php file with the database credentials, and running the browser-based install script at /wp-admin/install.php, which creates the database tables and the first administrator account.",
      codeExamples: [
        {
          title: "The database connection settings in wp-config.php",
          language: "php",
          code: "define( 'DB_NAME', 'wp_mydatabase' );\ndefine( 'DB_USER', 'wp_dbuser' );\ndefine( 'DB_PASSWORD', 'a-strong-password' );\ndefine( 'DB_HOST', 'localhost' );",
          explanation: "These four constants tell WordPress which database to connect to and with what credentials — getting any one of them wrong produces the classic 'Error establishing a database connection' message.",
        },
      ],
      realWorldUsage: "Most hosting providers offer a one-click WordPress installer (like Softaculous) that automates all of this, but developers working on local machines use tools like Local by Flywheel or XAMPP to install WordPress for development and testing before deploying to a live server.",
      commonMistakes: [
        {
          wrong: "Losing or mistyping the database name, username, or password when setting up wp-config.php.",
          right: "Copy database credentials directly from your hosting control panel into wp-config.php, or use the values a one-click installer already fills in automatically, to avoid the 'Error establishing a database connection' screen.",
          explanation: "WordPress cannot function without a correct, working connection to its database — this is the single most common cause of a broken installation for beginners.",
        },
      ],
      practice: {
        instructions: "Install WordPress locally using a tool like Local (by WP Engine) or on free hosting, complete the setup wizard, and log into the /wp-admin dashboard for the first time. Note down every piece of information the setup wizard asked for.",
        hint: "Local (localwp.com) is a free, beginner-friendly way to run WordPress on your own computer without needing live hosting.",
      },
      quiz: [
        {
          question: "What must exist before WordPress can be installed and functional?",
          options: ["A theme already activated", "A working database it can connect to", "At least one blog post", "A payment gateway"],
          correctIndex: 1,
          explanation: "WordPress needs a database to store all its content and settings; without one correctly configured, the install fails.",
        },
        {
          question: "What does the file wp-config.php primarily store?",
          options: ["The site's theme files", "Database connection credentials and core configuration", "Blog post content", "Plugin code"],
          correctIndex: 1,
          explanation: "wp-config.php holds the database name, user, password, host, and other core configuration constants WordPress needs on every request.",
        },
        {
          question: "A new WordPress install shows 'Error establishing a database connection.' What's the most likely cause?",
          options: [
            "The active theme is outdated",
            "Incorrect database credentials in wp-config.php",
            "No plugins are installed yet",
            "The permalink structure hasn't been set",
          ],
          correctIndex: 1,
          explanation: "This specific error almost always means the DB_NAME, DB_USER, DB_PASSWORD, or DB_HOST values in wp-config.php don't match a working database, so WordPress can't connect.",
        },
        {
          question: "A developer wants to test theme changes before touching a live client site. What's the best approach?",
          options: [
            "Edit the live site directly and hope nothing breaks",
            "Install WordPress locally (e.g. with Local) to test changes safely first",
            "Delete the live site and start over",
            "Skip testing since WordPress never breaks",
          ],
          correctIndex: 1,
          explanation: "Local development environments let you experiment freely without any risk to a live, client-facing site.",
        },
        {
          question: "A client's host offers a one-click WordPress installer. What does this tool actually automate?",
          options: [
            "Writing all future blog content",
            "Creating the database, uploading WordPress files, and running the setup wizard automatically",
            "Choosing a domain name",
            "Designing the site's logo",
          ],
          correctIndex: 1,
          explanation: "One-click installers handle the technical setup steps — database creation, file upload, and initial configuration — that would otherwise be done manually.",
        },
      ],
      rememberThis: "No working database, no working WordPress — everything else is built on top of that one connection.",
      keyTakeaways: [
        "Installing WordPress needs hosting, a database, and the WordPress core files.",
        "wp-config.php stores the database credentials WordPress connects with.",
        "Most hosts offer one-click installers that automate the whole process.",
        "Local development tools like Local or XAMPP let you install WordPress without live hosting.",
      ],
    },
      ],
    },
  ],
};

const wordpressAdministration: CurriculumModuleDef = {
  name: "WordPress Administration",
  description: "Running the day-to-day dashboard: content, media, users, and site-wide settings.",
  estimatedDuration: "1 week",
  topics: [
    {
      name: "Content Structure",
      lessons: [
    {
      title: "The WordPress Dashboard",
      description: "The control room every WordPress site is managed from.",
      estimatedMinutes: 14,
      difficulty: "BEGINNER",
      whatIsIt: "The Dashboard is the admin screen you see after logging into /wp-admin — a sidebar menu and central work area that gives you access to every part of managing a WordPress site: posts, pages, media, plugins, appearance, users, and settings.",
      whyItMatters: "Almost every task you'll ever do in WordPress — publishing content, installing a plugin, changing a setting — starts from somewhere in the Dashboard, so knowing your way around it before diving into specific features saves a huge amount of confusion later.",
      analogy: "The Dashboard is like the cockpit of a plane. A new pilot doesn't need to touch every switch on day one, but they need to know which panel controls navigation, which controls the engines, and which controls communications, so they can find the right control quickly under pressure.",
      simpleExample: "A new site owner logging in for the first time sees 'At a Glance' stats, a menu with Posts, Media, Pages, Comments, Appearance, Plugins, Users, Tools, and Settings running down the left side.",
      technicalExplanation: "The admin dashboard is served from wp-admin/index.php and every screen within it (edit.php for posts, upload.php for media, and so on) is a PHP file that checks the logged-in user's capabilities before rendering, ensuring users only see and access what their role permits.",
      codeExamples: [],
      realWorldUsage: "Content editors, site administrators, and developers all live in this same Dashboard daily — editors mostly stay in Posts/Pages/Media, while administrators also touch Plugins, Users, and Settings.",
      commonMistakes: [
        {
          wrong: "Randomly clicking through every settings screen on a live client site without understanding what a setting does.",
          right: "Test unfamiliar settings changes on a staging or local copy of the site first, or at minimum read what a setting does before saving it on a live site.",
          explanation: "Some Dashboard settings (like permalink structure or site URL) can break a live site's navigation or SEO if changed carelessly without understanding the consequence.",
        },
      ],
      practice: {
        instructions: "Log into a WordPress dashboard (local install or demo site) and write down what each of these menu items is used for, in your own words: Posts, Pages, Media, Appearance, Plugins, Users, Settings.",
        hint: "Hover over each menu item to see its submenu options before writing your description.",
      },
      quiz: [
        {
          question: "What is the WordPress Dashboard?",
          options: [
            "The public-facing homepage of a site",
            "The admin screen (wp-admin) used to manage all aspects of a site",
            "A plugin for site backups",
            "A theme customization tool only",
          ],
          correctIndex: 1,
          explanation: "The Dashboard is the central admin area reached via /wp-admin, from which every management task is performed.",
        },
        {
          question: "What determines which Dashboard menu items a logged-in user can see?",
          options: ["Their browser type", "Their assigned user role and capabilities", "The current theme", "The time of day"],
          correctIndex: 1,
          explanation: "WordPress checks a user's role/capabilities before displaying certain admin screens, so an Editor and an Administrator see different menu options.",
        },
        {
          question: "A new client asks where they should go to add a new blog article. Which Dashboard menu item is correct?",
          options: ["Appearance", "Posts", "Plugins", "Tools"],
          correctIndex: 1,
          explanation: "Blog articles are managed under the Posts menu, where new entries are created, edited, and published.",
        },
        {
          question: "A junior team member logs into wp-admin and doesn't see the Plugins menu at all. What's the most likely reason?",
          options: [
            "Plugins have been uninstalled from WordPress entirely",
            "Their user role doesn't have the capability to manage plugins",
            "The Dashboard is broken",
            "The site has no theme active",
          ],
          correctIndex: 1,
          explanation: "Dashboard menu items are shown or hidden based on the logged-in user's role/capabilities — non-admin roles typically can't see or access the Plugins screen.",
        },
        {
          question: "Before making an unfamiliar change in Settings on a live client site, what's the safest practice?",
          options: [
            "Just try it and see what happens",
            "Test it on a staging or local copy first, or confirm what the setting does beforehand",
            "Always contact WordPress.org support first",
            "Disable the internet connection first",
          ],
          correctIndex: 1,
          explanation: "Some settings (like permalinks or site URL) can break live functionality; testing changes safely elsewhere first avoids costly live-site mistakes.",
        },
      ],
      rememberThis: "Learn the cockpit before you fly — most WordPress work starts from the Dashboard sidebar.",
      keyTakeaways: [
        "The Dashboard (wp-admin) is the central hub for managing a WordPress site.",
        "Its main sections are Posts, Pages, Media, Appearance, Plugins, Users, Tools, and Settings.",
        "What a logged-in user sees depends on their assigned role.",
        "Understanding a setting before changing it prevents breaking a live site.",
      ],
    },
    {
      title: "Posts vs Pages",
      description: "WordPress's two core content types, and when to use each.",
      estimatedMinutes: 15,
      difficulty: "BEGINNER",
      whatIsIt: "Posts are time-based, chronological content — blog entries, news updates, articles — that typically show up in reverse date order on a blog feed. Pages are static, standalone content that doesn't depend on a publish date — like an 'About Us,' 'Contact,' or 'Home' page.",
      whyItMatters: "Choosing the wrong content type for the wrong content causes real problems: putting your 'Contact Us' info in a Post means it'll disappear off the blog feed over time as new posts push it down, when it should be a permanent, easy-to-find Page.",
      analogy: "Posts are like entries in a diary — dated, listed in order, meant to accumulate over time. Pages are like the labeled dividers in a binder — 'Contact,' 'About,' 'Services' — fixed sections that don't change position just because time passes.",
      simpleExample: "A restaurant's website has a Page for 'Our Menu' (rarely changes, no date relevance) and uses Posts for 'This Week's Specials' (time-sensitive, meant to be archived as new specials replace old ones).",
      technicalExplanation: "Both are stored in the same wp_posts database table, differentiated by the post_type column ('post' vs 'page'). Posts support categories, tags, and appear in RSS feeds and chronological archives by default; Pages support a hierarchical parent/child structure and page templates, but no categories/tags by default.",
      codeExamples: [
        {
          title: "Querying only Pages using WP_Query",
          language: "php",
          code: "$pages = new WP_Query( array(\n    'post_type'      => 'page',\n    'posts_per_page' => 10,\n) );",
          explanation: "Setting 'post_type' to 'page' tells WordPress's query engine to fetch Pages specifically, rather than the default 'post' type — this is the underlying mechanism that keeps the two content types distinct.",
        },
      ],
      realWorldUsage: "Nearly every WordPress site combines both: Pages for the permanent structure (Home, About, Services, Contact) and Posts for regularly updated content (blog articles, news, announcements).",
      commonMistakes: [
        {
          wrong: "Creating the 'About Us' section as a Post because it was the first content type the user noticed in the menu.",
          right: "Use a Page for static, non-dated content like About, Contact, or Services, and reserve Posts for time-based, frequently updated content like blog articles.",
          explanation: "Posts are designed to be archived chronologically and can get buried; core site structure pages need to stay permanently and predictably accessible via the main menu.",
        },
      ],
      practice: {
        instructions: "For a fictional photography business website, list five pieces of content it would need, and classify each as a Post or a Page, explaining why.",
        hint: "Consider: Home, About, Portfolio, Pricing, and a 'Behind the scenes from last weekend's shoot' update.",
      },
      quiz: [
        {
          question: "Which content type is best suited for a 'Contact Us' section?",
          options: ["A Post, because it needs a publish date", "A Page, because it's static and permanent", "Neither, it must be a plugin", "A Category"],
          correctIndex: 1,
          explanation: "Contact information doesn't depend on time and should remain permanently and predictably accessible — that's what Pages are for.",
        },
        {
          question: "What database column distinguishes a Post from a Page internally?",
          options: ["post_title", "post_type", "post_date", "post_author"],
          correctIndex: 1,
          explanation: "Both are stored in wp_posts, and the post_type column ('post' or 'page') is what differentiates them.",
        },
        {
          question: "A restaurant wants a page announcing 'This Weekend's Live Music Lineup' that should naturally get archived once the event passes. Should this be a Post or a Page?",
          options: [
            "A Page, so it stays permanently visible",
            "A Post, since it's time-based and should move into the chronological archive over time",
            "Neither, it needs a custom plugin",
            "A Category",
          ],
          correctIndex: 1,
          explanation: "Time-sensitive, one-off announcements are exactly what Posts are designed for — they naturally age out of the main feed as new content is published.",
        },
        {
          question: "A client complains their 'About Us' content sometimes disappears from view as they publish more blog updates. What's the likely misconfiguration?",
          options: [
            "The About Us content was created as a Post instead of a Page",
            "The site has too many plugins",
            "The domain's DNS is misconfigured",
            "The Media Library is full",
          ],
          correctIndex: 0,
          explanation: "Posts get pushed down the chronological feed as new posts are added; static content like About Us should be a Page so it stays permanently and predictably accessible.",
        },
        {
          question: "Which feature is available to Pages but not to Posts by default?",
          options: ["Categories", "Tags", "Parent/child hierarchy", "RSS feed inclusion"],
          correctIndex: 2,
          explanation: "Pages support a hierarchical parent/child structure (e.g. a 'Services' page with sub-pages), which Posts don't use by default.",
        },
      ],
      rememberThis: "Posts are diary entries that pile up over time; Pages are the labeled binder dividers that stay put.",
      keyTakeaways: [
        "Posts are chronological, time-based content shown in reverse date order.",
        "Pages are static, standalone content without a date dependency.",
        "Both share the wp_posts table but differ by post_type.",
        "Pages support parent/child hierarchy; Posts support categories and tags.",
      ],
    },
    {
      title: "Categories & Tags",
      description: "Organizing blog content so both visitors and search engines can navigate it.",
      estimatedMinutes: 14,
      difficulty: "BEGINNER",
      whatIsIt: "Categories are broad, hierarchical groupings for organizing Posts into major topics (like 'Recipes' or 'Travel'), while Tags are specific, non-hierarchical keywords describing details within a post (like 'vegan' or 'italy'). A post is usually in one or two categories but can have many tags.",
      whyItMatters: "Without categorization, a blog with hundreds of posts becomes an unsearchable pile. Categories and tags give visitors a way to browse related content and give search engines context about what a piece of content is about.",
      analogy: "Categories are like the labeled sections of a library — Fiction, History, Science — broad and few. Tags are like sticky notes a librarian adds inside individual books — 'World War II,' 'plot twist,' 'translated' — many small, specific descriptors that cut across sections.",
      simpleExample: "A cooking blog might have categories like 'Breakfast,' 'Dinner,' and 'Desserts,' while a single dessert post might carry tags like 'chocolate,' 'no-bake,' and '30-minutes-or-less.'",
      technicalExplanation: "Categories and Tags are both implemented as WordPress 'taxonomies' — Categories are hierarchical (support parent/child relationships) while Tags are non-hierarchical (flat). Both are stored in the wp_terms, wp_term_taxonomy, and wp_term_relationships tables, linking terms to individual posts.",
      codeExamples: [
        {
          title: "Displaying a post's categories in a theme template",
          language: "php",
          code: "<?php the_category( ', ' ); ?>",
          explanation: "This template tag outputs the current post's assigned categories as a comma-separated, linked list, letting visitors click through to a category archive.",
        },
      ],
      realWorldUsage: "News sites use categories for sections like 'Politics,' 'Sports,' and 'Technology,' while tags let them cross-reference specific people, events, or topics across those sections in a search or related-posts widget.",
      commonMistakes: [
        {
          wrong: "Creating a new, slightly-differently-worded tag for every single post (e.g. 'pasta-recipe', 'pasta-recipes', 'italian-pasta') instead of reusing existing ones.",
          right: "Reuse a consistent, curated set of tags across posts, checking existing tags before creating near-duplicates.",
          explanation: "A sprawling, inconsistent tag list defeats the purpose of tagging — it should group related content, not fragment it into dozens of nearly-identical, low-value tags.",
        },
      ],
      practice: {
        instructions: "For a fictional travel blog, design a category structure (3-5 broad categories) and a sample tag list (8-10 reusable tags) that could apply across multiple posts.",
        hint: "Categories might be regions (e.g. 'Asia', 'Europe'); tags might be themes (e.g. 'budget-travel', 'solo-trip', 'food').",
      },
      quiz: [
        {
          question: "Which of these is true about Categories in WordPress?",
          options: ["They are non-hierarchical", "They are hierarchical and meant for broad grouping", "They cannot be assigned to posts", "They replace tags entirely"],
          correctIndex: 1,
          explanation: "Categories support parent/child relationships and are designed for broad topic organization, unlike flat tags.",
        },
        {
          question: "What is a practical downside of creating dozens of near-duplicate tags?",
          options: [
            "WordPress will crash",
            "It fragments content into low-value groups instead of meaningfully organizing it",
            "Tags cost money in WordPress",
            "Posts can no longer be published",
          ],
          correctIndex: 1,
          explanation: "Overlapping, inconsistent tags dilute their usefulness for both navigation and SEO instead of creating clear, browsable groupings.",
        },
        {
          question: "A news site wants readers to browse all articles about 'Politics' in one place, while also being able to find every article mentioning a specific senator across sections. Which combination fits best?",
          options: [
            "Use only categories for both needs",
            "Use a 'Politics' category for the section, and a tag for the senator's name to cross-reference across sections",
            "Use only tags for both needs",
            "Create a separate Page for each senator",
          ],
          correctIndex: 1,
          explanation: "Categories organize broad sections while tags cut across them to connect related specific topics — exactly this kind of cross-referencing use case.",
        },
        {
          question: "A blogger wants a 'Recipes' section with subgroups like 'Recipes > Vegan' and 'Recipes > Desserts.' Which taxonomy feature enables this?",
          options: [
            "Tags, because they are flexible",
            "Categories, because they support hierarchical parent/child relationships",
            "The Media Library",
            "User roles",
          ],
          correctIndex: 1,
          explanation: "Only categories support hierarchy in WordPress by default, allowing parent categories with child subcategories.",
        },
        {
          question: "Where does WordPress store the relationship linking a specific post to its assigned categories and tags?",
          options: [
            "Inside the theme's CSS file",
            "In the wp_term_relationships table, linking terms to posts",
            "In wp-config.php",
            "In the Media Library",
          ],
          correctIndex: 1,
          explanation: "WordPress's taxonomy system uses wp_terms, wp_term_taxonomy, and wp_term_relationships tables to connect categories/tags to individual posts.",
        },
      ],
      rememberThis: "Categories are the library's sections; tags are the librarian's sticky notes inside the books.",
      keyTakeaways: [
        "Categories are hierarchical and used for broad topic grouping.",
        "Tags are flat, specific keywords describing details within a post.",
        "Both are taxonomies stored using WordPress's term system.",
        "Keep tag usage consistent to avoid fragmenting content into near-duplicates.",
      ],
    },
      ],
    },
    {
      name: "Media, Users & Settings",
      lessons: [
    {
      title: "The Media Library",
      description: "Where every image, video, and file uploaded to a WordPress site lives.",
      estimatedMinutes: 13,
      difficulty: "BEGINNER",
      whatIsIt: "The Media Library is WordPress's built-in file manager for anything you upload — images, PDFs, videos, audio — storing them centrally so they can be reused across multiple posts and pages instead of uploading the same file repeatedly.",
      whyItMatters: "Images are usually the heaviest part of a webpage; managing them badly (huge unoptimized files, no alt text, disorganized uploads) directly hurts page speed, accessibility, and SEO.",
      analogy: "The Media Library is like a shared office filing cabinet — once a document is filed, anyone in the office can pull the same copy for a different report, instead of every person printing and storing their own duplicate.",
      simpleExample: "A blogger uploads a header photo once to the Media Library, then reuses that exact same image in three different blog posts without re-uploading it each time.",
      technicalExplanation: "Uploaded files are stored on the server's filesystem (typically under /wp-content/uploads/, organized by year/month), while WordPress creates a corresponding 'attachment' post type entry in the database storing metadata (title, alt text, caption, file path). On upload, WordPress automatically generates multiple resized versions (thumbnail, medium, large) for responsive use.",
      codeExamples: [
        {
          title: "Inserting a responsive image from the Media Library in a template",
          language: "php",
          code: "<?php echo wp_get_attachment_image( $attachment_id, 'large' ); ?>",
          explanation: "This function outputs a fully-formed <img> tag for a given attachment ID, including srcset attributes for responsive image sizes WordPress generated automatically on upload.",
        },
      ],
      realWorldUsage: "Every image-heavy page — product photos in an online store, a photographer's portfolio, blog post headers — depends on the Media Library for storage, organization, and delivering appropriately-sized images to different devices.",
      commonMistakes: [
        {
          wrong: "Uploading full-resolution camera photos (often 5-10MB each) directly into posts without compressing them first.",
          right: "Compress and resize images to a reasonable file size (using a tool or a plugin like ShortPixel/Smush) before or during upload, and always add descriptive alt text.",
          explanation: "Oversized images are one of the leading causes of slow WordPress sites, hurting both user experience and search engine rankings; alt text is also essential for accessibility and image SEO.",
        },
      ],
      practice: {
        instructions: "Upload three images of different file sizes to a test WordPress Media Library, add descriptive alt text to each, and note how the file size after WordPress's automatic optimization compares to the original.",
        hint: "Check the 'Attachment Details' panel on the right when you click an image in the Media Library — it shows file size and dimensions.",
      },
      quiz: [
        {
          question: "What happens automatically when you upload an image to the Media Library?",
          options: [
            "Nothing, it stores only the original file",
            "WordPress generates multiple resized versions for responsive use",
            "It gets deleted after 30 days",
            "It's converted into a Page",
          ],
          correctIndex: 1,
          explanation: "WordPress automatically creates several resized copies (thumbnail, medium, large) so the right size can be served depending on context.",
        },
        {
          question: "Why does alt text matter for uploaded images?",
          options: [
            "It changes the file size",
            "It supports accessibility (screen readers) and image search SEO",
            "It's required for the image to display at all",
            "It automatically resizes the image",
          ],
          correctIndex: 1,
          explanation: "Alt text describes an image for screen readers and search engines, aiding both accessibility and SEO — it has no effect on whether the image displays.",
        },
        {
          question: "A client's page loads very slowly, and inspection shows several 8MB camera photos embedded directly. What should be done?",
          options: [
            "Nothing, image size doesn't affect load speed",
            "Compress and resize the images before/during upload using a tool or plugin",
            "Delete the Media Library entirely",
            "Convert the images into Pages",
          ],
          correctIndex: 1,
          explanation: "Oversized, uncompressed images are a leading cause of slow page loads; compressing and resizing them is the standard fix.",
        },
        {
          question: "A photographer uploads the same header image once and wants to use it on five different blog posts. What's the correct approach?",
          options: [
            "Upload the same file five separate times, once per post",
            "Upload it once to the Media Library and reuse that same attachment across all five posts",
            "Save it directly in the theme's folder instead",
            "Email the file to each post individually",
          ],
          correctIndex: 1,
          explanation: "The Media Library is designed for exactly this — upload once, reuse the same stored file and its resized versions across any number of posts or pages.",
        },
        {
          question: "A site fails an accessibility audit for missing image descriptions. Which Media Library field addresses this directly?",
          options: ["File name", "Alt text", "Upload date", "File size"],
          correctIndex: 1,
          explanation: "Alt text is read aloud by screen readers to describe an image to visually impaired visitors, directly addressing this kind of accessibility gap.",
        },
      ],
      rememberThis: "The Media Library is the shared filing cabinet — file it once, reuse it everywhere.",
      keyTakeaways: [
        "The Media Library centrally stores and manages all uploaded files.",
        "WordPress auto-generates multiple image sizes for responsive display.",
        "Oversized, uncompressed images are a leading cause of slow sites.",
        "Alt text is essential for accessibility and image SEO.",
      ],
    },
    {
      title: "Users & Roles",
      description: "Controlling who can do what on a WordPress site.",
      estimatedMinutes: 16,
      difficulty: "BEGINNER",
      whatIsIt: "WordPress lets you create multiple user accounts, each assigned a role — Administrator, Editor, Author, Contributor, or Subscriber — that determines exactly which actions that person is allowed to perform on the site.",
      whyItMatters: "Not everyone who touches a website should have the same level of access. A guest blogger shouldn't be able to delete plugins, and a client's marketing intern shouldn't be able to change site-wide settings — roles enforce the principle of giving people only the access they need.",
      analogy: "Think of a hotel's keycard system: the general manager's card opens every door (Administrator), housekeeping staff can access guest rooms but not the accounting office (Editor/Author), and a guest's card only opens their own room (Subscriber).",
      simpleExample: "A magazine site gives its writers the 'Author' role (they can write and publish their own posts) but reserves the 'Administrator' role for the technical lead who manages plugins and site settings.",
      technicalExplanation: "Each role is a named set of 'capabilities' (fine-grained permissions like edit_posts, publish_posts, manage_options). Administrator has all capabilities; Editor can manage all posts/pages including others'; Author can publish/manage only their own posts; Contributor can write but not publish their own posts; Subscriber can only manage their own profile. Capabilities can be customized further with code or plugins.",
      codeExamples: [
        {
          title: "Checking a capability before showing an admin action",
          language: "php",
          code: "if ( current_user_can( 'publish_posts' ) ) {\n    echo 'You can publish content.';\n}",
          explanation: "current_user_can() checks whether the logged-in user's role grants a specific capability, letting developers show or hide functionality based on permission rather than just checking the role name directly.",
        },
      ],
      realWorldUsage: "Agencies managing client sites routinely set clients up as Editors (full content control) while keeping Administrator access limited to the development team, preventing accidental changes to plugins or core settings.",
      commonMistakes: [
        {
          wrong: "Giving every team member the Administrator role 'just to be safe' or to avoid permission errors.",
          right: "Assign the least-privileged role that lets each person do their job — most content contributors only need Author, Editor, or Contributor, not Administrator.",
          explanation: "Excess Administrator accounts multiply the damage a mistake, a compromised password, or a malicious plugin install can cause, since Administrators can alter or break anything on the site.",
        },
      ],
      practice: {
        instructions: "For a company blog with a marketing manager, two freelance writers, and a developer, assign the most appropriate WordPress role to each and explain your reasoning for one of them.",
        hint: "Consider who needs to publish directly versus who should have their drafts reviewed first.",
      },
      quiz: [
        {
          question: "Which role can publish and manage only their own posts, but not others'?",
          options: ["Administrator", "Editor", "Author", "Subscriber"],
          correctIndex: 2,
          explanation: "Author can write and publish their own content but cannot edit or manage posts created by other users, unlike Editor.",
        },
        {
          question: "What does current_user_can() check in PHP?",
          options: [
            "Whether a plugin is installed",
            "Whether the logged-in user's role grants a specific capability",
            "Whether a post is published",
            "Whether the site has SSL enabled",
          ],
          correctIndex: 1,
          explanation: "It checks the logged-in user's granted capabilities, which is the recommended way to gate functionality by permission rather than by role name alone.",
        },
        {
          question: "An agency is setting up a client's account on a site they built. The client should be able to manage all content but not touch plugins or site settings. Which role fits best?",
          options: ["Administrator", "Editor", "Contributor", "Subscriber"],
          correctIndex: 1,
          explanation: "Editor grants full control over posts and pages (including others') without exposing plugin management or site-wide settings, matching this exact need.",
        },
        {
          question: "A guest writer should be able to draft an article but must have an editor review and publish it before it goes live. Which role enforces that workflow?",
          options: ["Administrator", "Author", "Contributor", "Subscriber"],
          correctIndex: 2,
          explanation: "Contributors can write and submit posts but cannot publish them directly, requiring someone with higher privileges to review and publish.",
        },
        {
          question: "Why is giving every team member the Administrator role considered a bad practice, even if it avoids permission errors?",
          options: [
            "Administrator accounts cost extra money",
            "It multiplies the damage a mistake, stolen password, or malicious plugin could cause",
            "WordPress only allows one Administrator per site",
            "It slows down the website automatically",
          ],
          correctIndex: 1,
          explanation: "The principle of least privilege limits blast radius — fewer Administrator accounts means fewer ways a mistake or compromise can affect the whole site.",
        },
      ],
      rememberThis: "Give every user the keycard that opens exactly the doors they need — nothing more.",
      keyTakeaways: [
        "WordPress roles (Administrator, Editor, Author, Contributor, Subscriber) control what a user can do.",
        "Roles are built from finer-grained 'capabilities' like edit_posts or manage_options.",
        "Assign the least-privileged role needed for each person's actual job.",
        "Limiting Administrator accounts reduces the damage from mistakes or compromises.",
      ],
    },
    {
      title: "Core Settings",
      description: "The site-wide configuration screens every WordPress site relies on.",
      estimatedMinutes: 15,
      difficulty: "BEGINNER",
      whatIsIt: "The Settings menu in the Dashboard controls site-wide configuration: General (site title, tagline, URL, timezone), Writing (default post category, format), Reading (homepage display, how many posts per page), Discussion (comment behavior), and Permalinks (the URL structure for posts and pages).",
      whyItMatters: "These settings affect the entire site at once, not a single page — getting Permalinks or the homepage display wrong, for instance, can make every single page on the site harder to find or index by search engines.",
      analogy: "Core Settings are like the master thermostat and circuit breaker panel for a whole building — a single change there affects every room at once, unlike adjusting one radiator in one office.",
      simpleExample: "In Settings > Reading, a business owner chooses to show a static 'Home' Page as their homepage instead of a chronological list of blog posts, which is what most non-blog business sites want.",
      technicalExplanation: "Permalinks settings determine the URL rewrite rules used to turn WordPress's internal query parameters into clean URLs (e.g. /?p=123 becomes /2026/09/my-post/ or /my-post/), which are stored and applied via the server's .htaccess file (Apache) or server block config (Nginx). General settings store core values like siteurl and blogname directly in the wp_options database table.",
      codeExamples: [
        {
          title: "Reading a core setting value in PHP",
          language: "php",
          code: "$site_name = get_bloginfo( 'name' );\necho 'Welcome to ' . $site_name;",
          explanation: "get_bloginfo() retrieves values configured in Settings > General (like the site title), letting theme and plugin code reference site-wide settings dynamically instead of hardcoding them.",
        },
      ],
      realWorldUsage: "Every new WordPress install should have its Permalinks set to a clean, SEO-friendly structure (like 'Post name') and its Reading settings configured to show the correct homepage before real content work begins.",
      commonMistakes: [
        {
          wrong: "Leaving Permalinks on the default '?p=123' structure, or changing an already-live site's permalink structure without setting up redirects.",
          right: "Set a clean permalink structure (e.g. Post name) early in a new project, and if you must change permalinks on a live site, set up 301 redirects from old URLs to avoid breaking existing links and SEO rankings.",
          explanation: "Ugly, non-descriptive URLs hurt both usability and SEO, while changing permalinks on a live, indexed site without redirects breaks every existing bookmark, backlink, and search result pointing to the old URLs.",
        },
      ],
      practice: {
        instructions: "On a test WordPress site, go through General, Reading, and Permalinks settings, and note which single setting in each screen you think would have the biggest impact on a real business site if configured incorrectly.",
        hint: "Consider what changing the 'Site Address (URL)' field or switching permalinks after launch would actually do.",
      },
      quiz: [
        {
          question: "What do Permalink settings control?",
          options: ["Comment moderation", "The URL structure used for posts and pages", "User roles", "Plugin activation"],
          correctIndex: 1,
          explanation: "Permalinks define how WordPress's internal content is turned into the URL structure visitors and search engines see.",
        },
        {
          question: "What's a risk of changing permalink structure on an already-live, indexed site?",
          options: [
            "The site becomes faster automatically",
            "Existing bookmarks, backlinks, and search rankings can break without redirects",
            "All plugins get deactivated",
            "Nothing changes for visitors",
          ],
          correctIndex: 1,
          explanation: "Changing URL structure without setting up 301 redirects breaks every old link pointing to the previous URLs, hurting both users and SEO.",
        },
        {
          question: "A business site's homepage is currently showing a chronological blog feed, but the owner wants a fixed welcome page instead. Which setting fixes this?",
          options: [
            "Settings > Permalinks",
            "Settings > Reading, setting a static Page as the homepage",
            "Settings > Discussion",
            "Settings > Writing",
          ],
          correctIndex: 1,
          explanation: "Settings > Reading controls whether the homepage displays the latest posts or a chosen static Page, which is exactly what this scenario needs.",
        },
        {
          question: "A site is getting flooded with spam comments on old posts. Which settings screen is most relevant to address this?",
          options: ["Settings > General", "Settings > Discussion", "Settings > Permalinks", "Settings > Reading"],
          correctIndex: 1,
          explanation: "Settings > Discussion controls comment behavior, including moderation rules, closing comments on old posts, and spam-related options.",
        },
        {
          question: "A developer needs to display the site's configured title dynamically inside a theme file rather than typing it by hand. What should they use?",
          options: [
            "Hardcode the title as plain text in the template",
            "get_bloginfo( 'name' ) to pull the value from Settings > General",
            "A category archive query",
            "current_user_can()",
          ],
          correctIndex: 1,
          explanation: "get_bloginfo('name') retrieves the site title configured in Settings > General, keeping the value dynamic and consistent if it's ever changed.",
        },
      ],
      rememberThis: "Core Settings is the master breaker panel — one flip there changes the whole building, not just one room.",
      keyTakeaways: [
        "Settings > General, Writing, Reading, Discussion, and Permalinks configure site-wide behavior.",
        "Permalinks determine the URL structure for all content.",
        "Reading settings decide whether the homepage is a blog feed or a static Page.",
        "Changing permalinks on a live site requires 301 redirects to avoid breaking links and SEO.",
      ],
    },
      ],
    },
  ],
};

export const curriculum: CurriculumCourseDef = {
  courseName: "WordPress Development",
  modules: [wordpressFundamentals, wordpressAdministration],
};
